target_nodes: 
  - vk-hub-test-agent-1
  - kueue-node

required_namespaces:
  - default
  - kube-system
  - interlink4
  - interlink-v
  - interlink-k

timeout_multiplier: 1

values:
  namespace: interlink4

  annotations: 
    slurm-job.knoc.io/flags: "--job-name=test-pod-cfg -t 2800  --ntasks=8 --nodes=1 --mem-per-cpu=2000"

  tolerations:
    - key: virtual-node.interlink/no-schedule
      operator: Exists
      effect: NoSchedule
    - key: accelerator
      operator: Exists
      effect: NoSchedule

